#!/bin/bash
# Gather immediate stats
cpu1=($(grep cpu[0-9] /proc/stat | awk '{ usage = $2 + $3 + $4 + $7 + $8; print usage, usage + $5 + $6 }'))
disk1=($(cat /proc/diskstats))
sleep 1

cpu2=($(grep cpu[0-9] /proc/stat | awk '{ usage = $2 + $3 + $4 + $7 + $8; print usage, usage + $5 + $6 }'))
disk2=($(cat /proc/diskstats))

# CPU
echo "[CPU]"
for (( i=0; i<${#cpu1[@]}; i+=2 )); do
    usage=$((cpu2[i] - cpu1[i]))
    total=$((cpu2[i+1] - cpu1[i+1]))
    percentage=$((100 * usage / total))
    printf "CPU$((i / 2)) usage:\t$percentage%%\n"
done

# Memory
ramAvail=$(($(grep MemAvailable /proc/meminfo | awk '{ print $2 }') / 1024))
ramTotal=$(($(grep MemTotal /proc/meminfo | awk '{ print $2 }') / 1024))
ramUsage=$((ramTotal - ramAvail))

swapAvail=$(($(grep SwapFree /proc/meminfo | awk '{ print $2 }') / 1024))
swapTotal=$(($(grep SwapTotal /proc/meminfo | awk '{ print $2 }') / 1024))
swapUsage=$((swapTotal - swapAvail))

echo
echo "[Memory]"
printf "RAM usage:\t$ramUsage/$ramTotal MiB\n"
printf "SWAP usage:\t$swapUsage/$swapTotal MiB\n"

# GPU
# Use first available DRM GPU
drmPath=/sys/class/drm/card[0-9]
if [ -f $drmPath/device/gpu_busy_percent ] && [ -f $drmPath/device/mem_info_vram_used ] && [ -f $drmPath/device/mem_info_vram_total ]; then
    gpuUsage=$(cat $drmPath/device/gpu_busy_percent)
    vramUsage=$(($(cat $drmPath/device/mem_info_vram_used) / 1024 / 1024))
    vramTotal=$(($(cat $drmPath/device/mem_info_vram_total) / 1024 / 1024))

    echo
    echo "[GPU]"
    printf "GPU usage:\t$gpuUsage%%\n"
    printf "VRAM usage:\t$vramUsage/$vramTotal MiB\n"
fi

# Disk
echo
echo "[Disk]"
for (( i=0; i<${#disk1[@]}; i+=20 ));
do
    if [[ "${disk1[i+2]}" != "${disk2[i+2]}" ]] || (( i >= ${#disk2[@]})); then
        continue
    fi

    read=$(((${disk2[i+5]}-${disk1[i+5]})*512))
    if (( $read < 1024 )); then
        read="$read B/s"
    elif (( $read < 1024*1024 )); then
        read=$((read/1024))
        read="$read KiB/s"
    elif (( $read < 1024*1024*1024 )); then
        read=$((read/1024/1024))
        read="$read MiB/s"
    else
        read=$((read/1024/1024/1024))
        read="$read GiB/s"
    fi

    write=$(((${disk2[i+9]}-${disk1[i+9]})*512))
    if (( $write < 1024 )); then
        write="$write B/s"
    elif (( $write < 1024*1024 )); then
        write=$((write/1024))
        write="$write KiB/s"
    elif (( $write < 1024*1024*1024 )); then
        write=$((write/1024/1024))
        write="$write MiB/s"
    else
        write=$((write/1024/1024/1024))
        write="$write GiB/s"
    fi

    if [[ "$read" != "0 B/s" || "$write" != "0 B/s" ]]; then
        printf "${disk1[i+2]} usg.:\tRead: ${read}\tWrite: ${write}\n"
    fi
done
